// Generated by CoffeeScript 1.9.1
(function() {
  var c99;

  c99 = c99 || {};

  c99.Game = (function() {
    var Count99Game;
    Count99Game = function() {
      var preloader, restartButton;
      console.log('count99 game starts');
      this.canvas = document.getElementById('game-canvas');
      this.stage = new createjs.Stage(this.canvas);
      this.stage.name = 'Main Stage';
      createjs.Touch.enable(this.stage);
      preloader = new c99.Preloader(this);
      preloader.loadGraphics();
      restartButton = document.getElementById('restart-button');
      return restartButton.onclick = (function(evt) {
        var gameOverScene;
        gameOverScene = document.getElementById("gameover");
        gameOverScene.classList.remove("gameover-appear");
        return this.gameInit();
      }).bind(this);
    };
    Count99Game.prototype.gameInit = function() {
      var i, j, ref, tile;
      this.nextCount = 1;
      this.totalTile = 3;
      this.nextCountLabel = document.getElementById('next-count');
      this.tileOnPress = function(evt) {
        console.log("Obj: " + evt.target + " clicked in Stage: " + this.stage);
        if (evt.target.name === this.nextCount) {
          this.stage.removeChild(evt.target.parent);
          this.stage.update();
          this.nextCount++;
          this.nextCountLabel.innerHTML = this.nextCount;
          if (this.nextCount > this.totalTile) {
            return this.gameOver();
          }
        }
      };
      for (i = j = ref = this.totalTile; ref <= 1 ? j <= 1 : j >= 1; i = ref <= 1 ? ++j : --j) {
        tile = new c99.GameObject(i);
        tile.x = Math.random() * (this.canvas.width - tile.width);
        tile.y = Math.random() * (this.canvas.height - tile.height);
        console.log("position: " + tile.x + " " + tile.y);
        tile.on('click', this.tileOnPress.bind(this));
        this.stage.addChild(tile);
      }
      return this.stage.update();
    };
    Count99Game.prototype.gameOver = function() {
      var gameOverScene;
      this.nextCount = 1;
      this.nextCountLabel.innerHTML = this.nextCount;
      gameOverScene = document.getElementById("gameover");
      return gameOverScene.classList.add("gameover-appear");
    };
    return Count99Game;
  })();

  c99.Preloader = (function() {
    var Preloader;
    Preloader = function(game) {
      this.game = game;
    };
    Preloader.prototype.loadGraphics = function() {
      var imageList, img, item, j, len, loadFiles, results;
      imageList = [
        {
          name: 'tile',
          path: 'image/tile.png'
        }, {
          name: 'hud',
          path: 'image/hud.png'
        }, {
          name: 'gameover',
          path: 'image/gameover.jpg'
        }, {
          name: 'bg',
          path: 'image/bg.png'
        }, {
          name: 'restartButton',
          path: 'image/restart-button.png'
        }
      ];
      loadFiles = 0;
      c99.graphics = {};
      results = [];
      for (j = 0, len = imageList.length; j < len; j++) {
        item = imageList[j];
        img = new Image();
        img.onload = (function(evt) {
          loadFiles++;
          console.log(evt.target.src + " loaded, progress=" + loadFiles + ", total=" + imageList.length);
          if (loadFiles === imageList.length) {
            return this.game.gameInit();
          }
        }).bind(this);
        img.src = item.path;
        results.push(c99.graphics[item.name] = item);
      }
      return results;
    };
    return Preloader;
  })();

  c99.GameObject = (function() {
    var GameObject, p;
    GameObject = function(number) {
      this.number = number;
      this.initialize();
    };
    p = GameObject.prototype = new createjs.Container;
    p.category = 'object';
    p.width = 80;
    p.height = 80;
    p.Container_initialize = p.initialize;
    p.initialize = function() {
      var img, numText;
      this.Container_initialize();
      img = new createjs.Bitmap(c99.graphics.tile.path);
      img.name = this.number;
      this.addChild(img);
      numText = new createjs.Text(this.number, '24px PFTempestaFiveCompressed-Regular,sans-serif', '#ac1000');
      numText.x = this.width / 2;
      numText.y = this.height / 2;
      numText.textAlign = 'center';
      numText.textBaseline = 'middle';
      this.addChild(numText);
    };
    return GameObject;
  })();

  window.onload = function() {
    var game;
    game = new c99.Game;
  };

}).call(this);
